POST http://127.0.0.1:3000/api/auth/register
Content-Type: application/json

{
    "firstName":"coba4",
    "lastName":"last",
    "nim":133,
    "username":"coba4",
    "email":"coba4@gmail.com",
    "password":"passcoba4"
}